//
//  Questions.swift
//  Chordie
//
//  Created by Ayo Moreira on 5/20/23.
//

import Foundation

var intervalQuestions = [
    "C": [
        "D is the 2 of": "C",
        "E is the 3 of": "C",
        "F is the 4 of": "C",
        "G is the 5 of": "C",
        "A is the 6 of": "C",
        "B is the 7 of": "C",
        "D is the 9 of": "C",
        "Db is the b9 of": "C",
        "D# is the #9 of": "C",
        "F is the 11 of": "C",
        "F# is the #11 of": "C",
        "A is the 13 of": "C",
        "Ab is the b13 of": "C",
    ],
    "Db": [
        "Eb is the 2 of": "Db",
        "F is the 3 of": "Db",
        "Gb is the 4 of": "Db",
        "Ab is the 5 of": "Db",
        "Bb is the 6 of": "Db",
        "C is the 7 of": "Db",
        "Eb is the 9 of": "Db",
        "D is the b9 of": "Db",
        "E is the #9 of": "Db",
        "Gb is the 11 of": "Db",
        "G is the #11 of": "Db",
        "Bb is the 13 of": "Db",
        "A is the b13 of": "Db",
    ],
    "D": [
        "E is the 2 of": "D",
        "F# is the 3 of": "D",
        "G is the 4 of": "D",
        "A is the 5 of": "D",
        "B is the 6 of": "D",
        "C# is the 7 of": "D",
        "E is the 9 of": "D",
        "Eb is the b9 of": "D",
        "F is the #9 of": "D",
        "G is the 11 of": "D",
        "G# is the #11 of": "D",
        "B is the 13 of": "D",
        "Bb is the b13 of": "D",
    ],
    "Eb": [
        "F is the 2 of": "Eb",
        "G is the 3 of": "Eb",
        "Ab is the 4 of": "Eb",
        "Bb is the 5 of": "Eb",
        "C is the 6 of": "Eb",
        "D is the 7 of": "Eb",
        "F is the 9 of": "Eb",
        "E is the b9 of": "Eb",
        "F# is the #9 of": "Eb",
        "Ab is the 11 of": "Eb",
        "A is the #11 of": "Eb",
        "C is the 13 of": "Eb",
        "B is the b13 of": "Eb",
    ],
    "E": [
        "F# is the 2 of": "E",
        "G# is the 3 of": "E",
        "A is the 4 of": "E",
        "B is the 5 of": "E",
        "C# is the 6 of": "E",
        "D# is the 7 of": "E",
        "F# is the 9 of": "E",
        "F is the b9 of": "E",
        "G is the #9 of": "E",
        "A is the 11 of": "E",
        "A# is the #11 of": "E",
        "C# is the 13 of": "E",
        "C is the b13 of": "E",
    ],
    "F": [
        "G is the 2 of": "F",
        "A is the 3 of": "F",
        "Bb is the 4 of": "F",
        "C is the 5 of": "F",
        "D is the 6 of": "F",
        "E is the 7 of": "F",
        "G is the 9 of": "F",
        "Gb is the b9 of": "F",
        "G# is the #9 of": "F",
        "Bb is the 11 of": "F",
        "B is the #11 of": "F",
        "D is the 13 of": "F",
        "Db is the b13 of": "F",
    ],
    "Gb": [
        "Ab is the 2 of": "Gb",
        "Bb is the 3 of": "Gb",
        "Cb is the 4 of": "Gb",
        "Db is the 5 of": "Gb",
        "Eb is the 6 of": "Gb",
        "F is the 7 of": "Gb",
        "Ab is the 9 of": "Gb",
        "G is the b9 of": "Gb",
        "A is the #9 of": "Gb",
        "Cb is the 11 of": "Gb",
        "C is the #11 of": "Gb",
        "Eb is the 13 of": "Gb",
        "D is the b13 of": "Gb",
    ],
    "G": [
        "A is the 2 of": "G",
        "B is the 3 of": "G",
        "C is the 4 of": "G",
        "D is the 5 of": "G",
        "E is the 6 of": "G",
        "F# is the 7 of": "G",
        "A is the 9 of": "G",
        "Ab is the b9 of": "G",
        "A# is the #9 of": "G",
        "C is the 11 of": "G",
        "C# is the #11 of": "G",
        "E is the 13 of": "G",
        "Eb is the b13 of": "G",
    ],
    "Ab": [
        "Bb is the 2 of": "Ab",
        "C is the 3 of": "Ab",
        "Db is the 4 of": "Ab",
        "Eb is the 5 of": "Ab",
        "F is the 6 of": "Ab",
        "G is the 7 of": "Ab",
        "Bb is the 9 of": "Ab",
        "A is the b9 of": "Ab",
        "B is the #9 of": "Ab",
        "Db is the 11 of": "Ab",
        "D is the #11 of": "Ab",
        "F is the 13 of": "Ab",
        "E is the b13 of": "Ab",
    ],
    "A": [
        "B is the 2 of": "A",
        "C# is the 3 of": "A",
        "D is the 4 of": "A",
        "E is the 5 of": "A",
        "F# is the 6 of": "A",
        "G# is the 7 of": "A",
        "B is the 9 of": "A",
        "Bb is the b9 of": "A",
        "C is the #9 of": "A",
        "D is the 11 of": "A",
        "D# is the #11 of": "A",
        "F# is the 13 of": "A",
        "F is the b13 of": "A",
    ],
    "Bb": [
        "C is the 2 of": "Bb",
        "D is the 3 of": "Bb",
        "Eb is the 4 of": "Bb",
        "F is the 5 of": "Bb",
        "G is the 6 of": "Bb",
        "A is the 7 of": "Bb",
        "C is the 9 of": "Bb",
        "B is the b9 of": "Bb",
        "C# is the #9 of": "Bb",
        "Eb is the 11 of": "Bb",
        "E is the #11 of": "Bb",
        "G is the 13 of": "Bb",
        "Gb is the b13 of": "Bb"
    ],
    "B": [
        "C# is the 2 of": "B",
        "D# is the 3 of": "B",
        "E is the 4 of": "B",
        "F# is the 5 of": "B",
        "G# is the 6 of": "B",
        "A# is the 7 of": "B",
        "C# is the 9 of": "B",
        "C is the b9 of": "B",
        "D is the #9 of": "B",
        "E is the 11 of": "B",
        "F is the #11 of": "B",
        "G# is the 13 of": "B",
        "G is the b13 of": "B"
    ]
]

var chordQuestions = [
    "C": [
        "C Maj7": "C E G B",
        "C Min7": "C Eb G Bb",
        "C Min7b5": "C Eb Gb Bb",
        "C Dim7": "C Eb Gb A",
        "C Sus4": "C F G Bb",
        "C DimMaj7": "C Eb Gb B",
        "C MinMaj7": "C Eb G B",
        "C7": "C E G Bb"
    ],
    "Db": [
        "Db Maj7": "Db F Ab C",
        "Db Min7": "Db E Ab B",
        "Db Min7b5": "Db E G B",
        "Db Dim7": "Db E G Bb",
        "Db Sus4": "Db Gb Ab B",
        "Db DimMaj7": "Db E G C",
        "Db MinMaj7": "Db E Ab C",
        "Db7": "Db F Ab B",
    ],
    "D": [
        "D Maj7": "D F# A C#",
        "D Min7": "D F A C",
        "D Min7b5": "D F Ab C",
        "D Dim7": "D F Ab B",
        "D Sus4": "D G A C",
        "D DimMaj7": "D F Ab C#",
        "D MinMaj7": "D F A C#",
        "D7": "D F# A C",
    ],
    "Eb": [
        "Eb Maj7": "Eb G Bb D",
        "Eb Min7": "Eb Gb Bb Db",
        "Eb Min7b5": "Eb Gb A Db",
        "Eb Dim7": "Eb Gb A C",
        "Eb Sus4": "Eb Ab Bb Db",
        "Eb DimMaj7": "Eb Gb A D",
        "Eb MinMah7": "Eb Gb Bb D",
        "Eb7": "Eb G Bb Db",
    ],
    "E": [
        "E Maj7": "E G# B D#",
        "E Min7": "E G B D",
        "E Min7b5": "E G Bb D",
        "E Dim7": "E G Bb C#",
        "E Sus4": "E A B D",
        "E DimMaj7": "E G Bb D#",
        "E MinMaj7": "E G B D#",
        "Eb7": "E G B D#"
    ],
    "F": [
        "F Maj7": "F A C E",
        "F Min7": "F Ab C Eb",
        "F Min7b5": "F Ab B Eb",
        "F Dim7": "F Ab B D",
        "F Sus4": "F G C Eb",
        "F DimMaj7": "F Ab B E",
        "F MinMaj7": "F Ab C E",
        "F7": "F A C Eb"
    ],
    "Gb": [
        "Gb Maj7": "Gb Bb Db F",
        "Gb Min7": "Gb A Db E",
        "Gb Min7b5": "Gb A C E",
        "Gb Dim7": "Gb A C Eb",
        "Gb Sus4": "Gb B Db E",
        "Gb DimMaj7": "Gb A C F",
        "Gb MinMaj7": "Gb A Db F",
        "Gb7": "Gb Bb Db E"
    ],
    "G": [
        "G Maj7": "G B D F#",
        "G Min7": "G Bb D F",
        "G Min7b5": "G Bb Db F",
        "G Dim7": "G Bb Db E",
        "G Sus4": "G C D E",
        "G DimMaj7": "G Bb Db F#",
        "G MinMaj7": "G Bb D F#",
        "G7": "G B D F"
    ],
    "Ab": [
        "Ab Maj7": "Ab C Eb G",
        "Ab Min7": "Ab B Eb Gb",
        "Ab Min7b5": "Ab B D Gb",
        "Ab Dim7": "Ab B D F",
        "Ab Sus4": "Ab Db Eb Gb",
        "Ab DimMaj7": "Ab B D G",
        "Ab MinMaj7": "Ab B Eb G",
        "Ab7": "Ab C Eb Gb"
    ],
    "A": [
        "A Maj7": "A C# E G#",
        "A Min7": "A C E G",
        "A Min7b5": "A C D# G",
        "A Dim7": "A C D# F#",
        "A Sus4": "A D E G",
        "A DimMaj7": "A C D# G#",
        "A MinMaj7": "A C E G#",
        "A7": "A C# E G"
    ],
    "Bb": [
        "Bb Maj7": "Bb D F A",
        "Bb Min7": "Bb Db F Ab",
        "Bb Min7b5": "Bb Db E Ab",
        "Bb Dim7": "Bb Db E G",
        "Bb Sus4": "Bb Eb F Ab",
        "Bb DimMaj7": "Bb Db E A",
        "Bb MinMaj7": "Bb Db F A",
        "Bb7": "Bb D F Ab"
    ],
    "B": [
        "B Maj7": "B D# F# A#",
        "B Min7": "B D F# A",
        "B Min7b5": "B D F A",
        "B Dim7": "B D F Ab",
        "B Sus4": "B E F A",
        "B DimMaj7": "B D F A#",
        "B MinMaj7": "B D F# A#",
        "B7": "B D# F# A"
    ]
]

var tensionQuestions = [
    "9 - #11 - 13": "Maj7",
    "9 - 11 - 13": "Min7",
    "b9 - 9 - #9 - T11 - #11 - b13 - 13": "Dom7",
    "9 - 11": "Min7b5",
    "b9 - 9 - 11 - b13": "Dim7",
    "9 - 13": "Sus4",
    "9": "DimMaj7 / MinMaj7"
]

var lowIntervalLimitQuestions = [
    "Min 2nd (b2)": "C#3",
    "Maj 2nd": "C3",
    "Min 3rd (b3)": "A2",
    "Maj 3rd": "Ab2",
    "Perf 4": "G2",
    "Min 5th (b5)": "C3",
    "Perf 5th": "E1",
    "Min 6th (b6)": "C2",
    "Perf 6th": "D2",
    "Min 7th (b7)": "Db2",
    "Maj 7": "Eb2",
    "Octave": "Infinite"
]


